FROM alpine:3.20 AS builder


RUN apk add --no-cache shellcheck

WORKDIR /build
COPY backup.sh .
COPY restore.sh .
COPY entrypoint.sh .
COPY crontab.txt .


RUN shellcheck -S error backup.sh restore.sh entrypoint.sh


RUN test -s crontab.txt || (echo "ERRO: crontab.txt vazio ou ausente" && exit 1)


RUN sed -i 's/\r$//' backup.sh restore.sh entrypoint.sh
RUN chmod +x backup.sh restore.sh entrypoint.sh



FROM alpine:3.20


RUN apk add --no-cache mysql-client tzdata dcron tini
ENV TZ=America/Sao_Paulo

COPY --from=builder --chmod=755 /build/backup.sh /backup.sh
COPY --from=builder --chmod=755 /build/restore.sh /restore.sh
COPY --from=builder --chmod=755 /build/entrypoint.sh /entrypoint.sh
COPY --from=builder /build/crontab.txt /etc/crontabs/root
RUN chmod 600 /etc/crontabs/root
RUN apk add --no-cache apache2-utils

COPY load-test.sh /load-test.sh

RUN chmod +x /load-test.sh
ENTRYPOINT ["/sbin/tini", "--", "/entrypoint.sh"]



CMD ["crond", "-f", "-L", "/dev/stdout"]